FROM oven/bun:1

WORKDIR /usr/src/app

ARG DATABASE_URL
COPY ./packages ./packages
COPY  ./bun.lock ./bun.lock
COPY  ./package.json ./package.json
COPY  ./package-lock.json ./package-lock.json
COPY  ./turbo.json ./turbo.json

RUN bun install

COPY ./apps/web ./apps/web

RUN bun run db:generate

# Debugging steps
RUN echo "DATABASE_URL is ${DATABASE_URL}"
RUN bun --version
RUN ls -la /usr/src/app

RUN DATABASE_URL=${DATABASE_URL} bun run build

EXPOSE 3000
CMD ["bun", "run", "start:web"]



