name : Continuous Deployment ws (prod)

on :
    push :
        branches : [ main ]

jobs :
    build:
        runs-on : ubuntu-latest
        steps:
            - name : Checkout Code
              uses : actions/checkout@v2

            - name : Log in Docker Hub
              uses : docker/login-action@v2
              with :
                username : ${{ secrets.DOCKERHUB_USERNAME }}
                password : ${{ secrets.DOCKERHUB_SECRET }}
            
            - name : build and push
              uses : docker/build-push-action@v2
              with :
                context : .
                file : ./docker/DockerFile.ws
                push : true
                tags: omega840/dummy-ws:${{github.sha}}
